### ISSUE TITLE
worker crashed

### ISSUE THREAD

**Issue by vanloswang** [OnApp/provisioner#72]
The version of ansible is ansible1.9-1.9.6-2.el7.noarch.
```bash
# python -u ./worker.py  
Got task 'docker' for root@192.168.1.16 (attempt: 1, uuid: 2ac82626-bf89-4743-87ee-884fde7f3aa7)
Traceback (most recent call last):
  File "./worker.py", line 199, in <module>
    main()
  File "./worker.py", line 195, in main
    task_router(task)
  File "./worker.py", line 147, in task_router
    only_tags=only_tags,
  File "/root/provisioner-master/lib/ansible_helper.py", line 129, in provision
    extra_vars=extra_vars
  File "/root/provisioner-master/lib/ansible_helper.py", line 78, in run_playbook
    only_tags=only_tags,
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 103, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 476, in _load_roles
    raise errors.AnsibleError("found role at %s, but cannot find %s or %s or %s or %s or %s or %s" % (role_path, task, handler, vars_file, defaults_file, meta_file, library))
ansible.errors.AnsibleError: found role at /root/provisioner-master/provision_profiles/roles/unattended-upgrades, but cannot find /root/provisioner-master/provision_profiles/roles/unattended-upgrades/tasks/main or /root/provisioner-master/provision_profiles/roles/unattended-upgrades/handlers/main or /root/provisioner-master/provision_profiles/roles/unattended-upgrades/vars/main or /root/provisioner-master/provision_profiles/roles/unattended-upgrades/defaults/main or /root/provisioner-master/provision_profiles/roles/unattended-upgrades/meta/main or /root/provisioner-master/provision_profiles/roles/unattended-upgrades/library
```

**Comment by vpetersson** [comment]
There are a number of settings you need to do in order for that to work, so just switch to running it in Docker.
